version: '3.4'

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: indicators_storage_nginx
    restart: unless-stopped
    networks:
      - indicators_storage
    depends_on:
      - php
    ports:
      - '84:80'
    volumes:
      - ./:/opt/app
      - ./build/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    image: mysql:8.0.17
    container_name: indicators_storage_mysql
    restart: unless-stopped
    networks:
      - indicators_storage
    volumes:
      - ./storage/database:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3309:3306'

  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    container_name: indicators_storage_php
    networks:
      - indicators_storage
    depends_on:
      - mysql
    volumes:
      - .:/opt/app:delegated
    env_file:
      - .env

networks:
  indicators_storage:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400
